version: '3'

services:
  mysql:
    container_name: mysql_house
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: 'jhkang1313.iptime.org'
      MYSQL_USER: "root"

      MYSQL_DATABASE: "kang"
    ports:
      - "13306:13306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "collation-server=utf8mb4_unicode_ci"
