spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://jhkang1313.iptime.org:13306/kang
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234!

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl_auto: none

  batch:
    jdbc:
      initialize-schema: ALWAYS
---
spring:
  config:
    activate:
      on-profile: text
  jpa:
    database: h2
